# This is a basic workflow to help you get started with Actions

name: staticPage

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]
   
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Deploy static to Tencent CloudBase
        uses: TencentCloudBase/cloudbase-action@v1
        with:
          secretId: ${{ secrets.SECRET_ID }}
          secretKey: ${{ secrets.SECRET_KEY }}
          envId: ${{ secrets.ENV_ID }}
          staticSrcPath: ./
      - name: Get the deploy result
        run: echo "Deploy to cloudbase result ${{ steps.deployStatic.outputs.deployResult }}"
